name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'test2.md'
        destination_repo: 'SatishNitk/second-repo'
        destination_folder: 'test-dir'
        user_email: 'satishkrgu95@gmail.com'
        user_name: 'satishNitk'
        commit_message: 'A custom message for the commit'
